//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTG_Card
    {
        public string card_name { get; set; }
        public Nullable<decimal> cmc { get; set; }
        public string mci_number { get; set; }
        public string mana_cost { get; set; }
        public string card_id { get; set; }
        public string flavor_text { get; set; }
        public string power { get; set; }
        public string toughness { get; set; }
        public string card_rarity { get; set; }
        public string card_layout { get; set; }
        public string card_type { get; set; }
        public string card_subtype { get; set; }
        public string card_text { get; set; }
        public Nullable<int> multiverse_id { get; set; }
        public string card_colors { get; set; }
        public string card_color_identity { get; set; }
        public string card_artist { get; set; }
        public string sets { get; set; }
        public int id { get; set; }
    }
}
